### PR TITLE
removed extra square where no element exists, see https://sr.ht/35C0.png

### PR DESCRIPTION
**Pull request by MaxLeiter**

### CODE REVIEW

**Comment by ddevault** [comment]
What? Barium is definitely an element...

**Comment by MaxLeiter** [comment]
Barium still exists; it's the selected element in the image.

Currently, the square is automatically skipped over by the program, this PR just stops the square from being drawn.

**Comment by ddevault** [comment]
What extra square did you remove? Can I see a before and after?

**Comment by MaxLeiter** [comment]
https://i.imgur.com/MP0Zuzv.png The square to the right of barium (selected) is just skipped over, un-selectable

**Comment by ddevault** [comment]
Oh, I see. Thanks. This behavior is actually intentional.

**Comment by Mechtecs** [comment]
lel

**Pull request closed without merging**
